inherit_gem:
  rubocop-inst:
  - rubocop.yml
  - rubocop-rspec.yml

plugins:
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

Naming/FileName:
  Exclude:
    - lib/mqtt-homie-homeassistant.rb

Style/Documentation:
  Enabled: false
