inherit_gem:
  rubocop-inst:
  - rubocop.yml

require:
  - rubocop-rake

AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Naming/FileName:
  Exclude:
    - lib/mqtt-homie-homeassistant.rb

Style/BlockDelimiters:
  AllowedMethods: []
Style/DocumentDynamicEvalDefinition:
  Enabled: false
Style/Documentation:
  Enabled: false
